---
# Install tasks for ansible-role-ubuntu display
- name: Export display to use
  command: export DISPLAY=:0
  ignore_errors: true

- name: Disable Screensaver delay 
  command: gsettings set org.gnome.desktop.session idle-delay 0

- name: Disable Screensaver lock  
  command: gsettings set org.gnome.desktop.screensaver lock-enabled false

- name: Disable Screensaver altogether  
  command: xset s off 
  ignore_errors: true
